[package]
name = "tracing-subscriber-config2"
description = "Serializable configuration and runtime composition for tracing-subscriber layer factories"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
version = "0.2.0"
readme = "README.md"
repository.workspace = true

[dependencies]
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde-value = "0"
thiserror = "2"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter", "fmt", "registry"] }
